### ISSUE TITLE
bug during startup in devmode

### ISSUE THREAD

**Issue by rnenjoy** [loonpwn/nuxt-build-optimisations#6]
**Describe the bug**
 ERROR  config.module.rules[ruleKey].use.filter is not a function                                                                  15:46:34

  at node_modules/nuxt-build-optimisations/dist/index.js:2160:54
  at Array.forEach (<anonymous>)
  at Array.esbuildOptimiser (node_modules/nuxt-build-optimisations/dist/index.js:2156:25)
  at WebpackBundler.<anonymous> (node_modules/nuxt-build-optimisations/dist/index.js:2248:28)
  at next (node_modules/@nuxt/utils/dist/utils.js:1879:27)
  at WebpackBundler.<anonymous> (node_modules/@nuxt/utils/dist/utils.js:1894:12)
  at WebpackBundler.<anonymous> (node_modules/@nuxt/utils/dist/utils.js:1888:29)
  at WebpackClientConfig.extendConfig (node_modules/@nuxt/webpack/dist/webpack.js:4879:37)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:4914:45)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:5078:26)
  at WebpackBundler.getWebpackConfig (node_modules/@nuxt/webpack/dist/webpack.js:5386:19)
  at WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:5393:12)
  at Builder.build (node_modules/@nuxt/builder/dist/builder.js:5634:30)
  at async Object._buildDev (node_modules/@nuxt/cli/dist/cli-dev.js:106:5)
  at async Object.startDev (node_modules/@nuxt/cli/dist/cli-dev.js:64:7)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-dev.js:51:5)

**Comment by loonpwn** [comment]
Thank you @rnenjoy. Patch will be in the next release

I'm not exactly sure why your webpack config doesn't look like the default nuxt's, so I can't guarantee this will fix it. But please let me know how it goes.

**Comment by rnenjoy** [comment]
Is it the nuxt config that is special for me or some other file I can check? I'm interested too why I'm special 😂
